---
title: "Examen sesiunea 6 - 11 iunie 2017"
subtitle: "Timp de lucru 2h^[Toate documentele și calculatoarele electronice de mână sunt autorizate. Computerele personale, telefoanele mobile/smartwatch-urile sunt **strict interzise**.]"
output:
  pdf_document:
    includes:
      before_body: Defs/body.tex
      in_header: Defs/FormatAndDefs.tex
    keep_tex: yes
    toc: no
  html_document:
    fig_caption: yes
    toc: yes
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)

# Exercitiul 1: Rosner pag 471 example 11.15
# Exercitiul 2: Culegere probleme stat - Aida Toma et al Ex 8 / 331
# Exercitiul 3: 
```

<style type="text/css">
.table {
    margin: auto;
    width: 40%;

}

</style>

### Exercițiul 1

Spirometria este o tehnică medicală neinvazivă folosită pentru diagnosticul și monitorizarea bolilor plămânului. O măsură standard înregistrată de spirometru este *capacitatea vitală forțată* (FVC). Pentru a identifica persoane cu o funcționare anormală a plămânilor, au fost stabilite valori standard ale FVC la persoanele normale. În general, FVC depinde atât de vârsta pacientului cât și de înălțimea acestuia. Un studiu a fost efectuat asupra băieților cu vârste cuprinse între 10 și 15 ani din regiunea Tecumseh, Michigan și vrem să postulăm un model liniar de tipul $FVC = \alpha + \beta*(înălțime) + \varepsilon$. Următorul tabel prezintă media FVC pentru grupe de înălțime de câte 4 cm. 

Găsiți dreapta de regresie și testați semnificația acesteia. Care este proporția din varianța lui FVC care poate fi explicată de înălțime ? 


\begin{center}
\begin{table}[ht]
\centering
  \begin{tabular}{cccc}
  \toprule
    Inaltime & Medie FVC & Inaltime & Medie FVC\\
    (cm) & (L) & (cm) & (L)\\
  \midrule
    134 & 1.7 & 158 & 2.7\\
    138 & 1.9 & 162 & 3.0\\
    142 & 2.0 & 166 & 3.1\\
    146 & 2.1 & 170 & 3.4\\
    150 & 2.2 & 174 & 3.8\\
    154 & 2.5 & 178 & 3.9\\
  \bottomrule
    
  \end{tabular}
\end{table}
\end{center}

### Exercițiul 2

Pentru a determina calitatea lânei se măsoară conținutul de biosulfit ($X$) și conținutul de apă saturată ($Y$), amândouă fiind date în procente. Să se găsească dreapta de regresie a lui $Y$ în raport cu $X$ pe baza următoarelor date:

\begin{center}
\begin{table}[ht]
\centering
  \begin{tabular}{c|cccccccc}
    $x_i$ & 10 & 15 & 30 & 40 & 50 & 55 & 80 & 100\\
    \hline
    $y_i$ & 50 & 46 & 43 & 43 & 36 & 39 & 37 & 33
  \end{tabular}
\end{table}
\end{center}

