---
title: "Statistică"
author: "Alex Amărioarei, Georgiana Popovici"
date: "2016-2017"
output:
  html_document:
    fig_caption: yes
    toc: yes
    toc_float:
      collapsed: no
  pdf_document:
    keep_tex: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Informații generale

Acest curs reprezintă o introducere în statistica matematică.  

### Informații de contact 

#### Curs 

 *  _Instructor_ : [Alexandru Amărioarei](https://alexamarioarei.github.io/)

 *  _Email_ : amarioareialexandru [at] gmail [dot] com

 *  _Orar_ : Vineri 14:00 - 16:00

 *  _Sala_ : Sala 219 (Etaj 2) - Grupele 301, 311, 321


#### Seminar/Laborator

 *  _Instructori_ : [Alexandru Amărioarei](https://alexamarioarei.github.io/) și Georgiana Popovici

 *  _Email_ : amarioareialexandru [at] gmail [dot] com 

### Teme

Temele vor fi postate săptămânal. Este încurajată colaborarea între studenți dar fiecare trebuie să 
își scrie propriile soluții. Copierea temei este __interzisă__.

  1. [Tema 1](homework/Tema_1.pdf) pentru *Vineri 21 Octombrie*
  
Trimiterea temelor se poate face pe adresa de [Dropbox](https://www.dropbox.com/sh/il9vakxnex13qw5/AAAGi7ykDU1mtVFxunutwkBha?dl=0). Studenții trebuie să trimită temele în folderele cu grupele corespunzătoare. 
<!-- **Observație** Temele vor fi trimise pe adresa de email a instructorului până cel târziu la data menționată (ora 24) de către șefii de grupă. Aceștia vor aduna în prealabil temele de la colegi și vor crea o arhiva cu numele *grupa_x_tema_y.zip*. În interiorul arhivei ar trebuie sa se găsească un număr de foldere egal cu numărul de studenți care trimit tema, fiecare folder având numele studentului.  -->

### Proiecte de laborator

Informații suplimentare se vor afișa în curând...

### Notarea

Notarea se va face după cum urmează: teme (25%), mini proiecte (25%) și examen final (50%).

### Bibliografie

  1. Monica Dumitrescu, Anton Batatorescu - *Applied statistics using the R system*, Ed. Univ. Buc., 2006
  2. Virgil Craiu - *Statistică Matematică*, Ed. Univ. Buc., 1997
  3. Georgiana Popovici - *Statistical Labs using R-system*, Ed. Univ. Buc.
  4. George Casella, Roger Berger - *Statistical Inference*, Duxbury
  5. George Roussas - *A Course in Mathematical Statistics*, Academic Press, 1997
  6. Geoffrey Grimmett, David Stirzaker - *Probability and Random Processes*
  7. John Rice - *Mathematical Statistics and Data Analysis*, Duxbury
  

### Link-uri utile

#### R
  1. Programul R - [CRAN](https://cran.r-project.org/)
  2. Interfața grafică [RStudio](https://www.rstudio.com/)
  3. Documentație R (în engleză) - [R-Intro](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf)
  4. Documentație R (în română) - [R pentru începători ](ftp://cran.r-project.org/pub/R/doc/contrib/Paradis-rdebuts_RO.pdf)
  5. Documentație R (în română) - [Inițiere în R pentru persoane cu pregătire matematică ](http://www.edumanager.ro/community/documente/initiere_in_r.pdf)
  
#### Latex
  1. Introducere în Latex (în romană) - [Manual Wikibooks](https://ro.wikibooks.org/wiki/LaTeX_(carte))
  2. Introducere în Latex (în engleză) - [Wikibooks Latex Manual](https://en.wikibooks.org/wiki/LaTeX) în special secțiunile de [matematică](https://en.wikibooks.org/wiki/LaTeX/Mathematics), [liste](https://en.wikibooks.org/wiki/LaTeX/List_Structures), [grafice](https://en.wikibooks.org/wiki/LaTeX/Importing_Graphics) și [figuri](https://en.wikibooks.org/wiki/LaTeX/Floats,_Figures_and_Captions)
  3. Tutoriale Latex (în engleză) - [video](https://www.youtube.com/playlist?list=PLDD406480D35CE390)
  4. Editoarele: [Texmaker](http://www.xm1math.net/texmaker/download.html) și [TeXnicCenter](http://www.texniccenter.org/) 
  5. Mediul latex [MiKTeX](https://miktex.org/)

#### Rmarkdown
  1. Pachetul [Rmarkdown](http://rmarkdown.rstudio.com/index.html) pentru documente reproductibile
