---
title: "Tema 2"
subtitle: "Soluții"
output:
  pdf_document:
    includes:
      before_body: Defs/body.tex
      in_header: Defs/FormatAndDefs.tex
    keep_tex: yes
    toc: no
  html_document:
    fig_caption: yes
    toc: yes
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Exerci\c tiul 1

Observ\u am c\u a pentru $\om\in\{|X|\geq a\}$ avem $\om\in\{g(|X|\geq g(a)\}$ deoarece func\c tia $g$ este cresc\u atoare, prin urmare folosind monotonia m\u asurii de probabilitate $\PP(|X|\geq a)\leq\PP(g(|X|\geq g(a))$. Dac\u a consider\u am $A=\{g(|X|\geq g(a)\}$, atunci $g(|X|)\geq g(a)\1_{A}$ ceea ce implic\u a $\EE[g(|X|)]\geq g(a)\EE[\1_A]=g(a)\PP(A)$. Ultima rela\c tie arat\u a c\u a $\PP(A)\leq\frac{\EE[g(|X|)]}{g(a)}$, deoarece pentru $a>0$ avem $g(a)>0$ ($g$ este strict cresc\u atoare \c si pozitiv\u a). In final ob\c tinem
$$
\PP(|X|\geq a)\leq\PP(g(|X|\geq g(a))=\PP(A)\leq\frac{\EE[g(|X|)]}{g(a)}.
$$

### Exerci\c tiul 2

  a) Dac\u a i) este adev\u arat\u a atunci $p_n=e^{-\l}\frac{\l^n}{n!}$ de unde ob\c tinem imediat ii). Reciproc, presupunem ii) adev\u arat\u a \c si avem c\u a $\frac{p_n}{p_0}=\frac{p_1}{p_0}\frac{p_2}{p_1}\cdots\frac{p_n}{p_{n-1}}=\frac{\l^n}{n!}$ de unde $p_n=p_0\frac{\l^n}{n!}$. Cum $\sum_{k=0}^{\infty}p_k=1$ ob\c tinem c\u a $p_0=e^{-\l}$ \c si putem s\u a concluzion\u am.
  
  b)
  
    i) \c Stim c\u a $\PP(X=j)=\frac{\l^j}{j!}e^{-\l}$ \c si vrem s\u a evalu\u am raportul $\frac{\PP(X=j)}{\PP(X=j-1)}$:
$$
\frac{\PP(X=j)}{\PP(X=j-1)}=\frac{\frac{\l^j}{j!}e^{-\l}}{\frac{\l^{j-1}}{(j-1)!}e^{-\l}}=\frac{\l}{j}.
$$
Putem observa c\u a
$$
\begin{array}{ll}
     \PP(X=j)\geq\PP(X=j-1), & \mbox{dac\u a $\l\geq j$}\\
      \PP(X=j)<\PP(X=j-1), & \mbox{dac\u a $\l<j$}.\end{array}
      $$
ceea ce arat\u a c\u a $j=[\l]$ este punctul maxim \c si $\PP(X=[\l])=\frac{\l^{[\l]}}{[\l]!}e^{-\l}$ este valoarea maxim\u a. 
    
    ii) Dup\u a cum am v\u azut la punctul precedent avem $\frac{\PP(X=j)}{\PP(X=j-1)}=\frac{\l}{j}$. Dac\u a $j>0$ este fixat atunci putem observa c\u a maximum este atins pentru $\l=j$.
    
  c) Dac\u a $X\sim Geom(p)$ atunci $X=\sum_{k\geq1}p(1-p)^{k-1}\e_{k}$, unde $\e_k$ este m\u asura Dirac in $k$. Avem 
$$
  \EE\left[\frac{1}{X}\right] = \EE\left[\frac{1}{1+X-1}\right] = \EE\left[\int_{0}^{1}t^{X-1}\,dt\right] = \int_{0}^{1}\EE[t^{X-1}]\,dt
$$
iar 
$$
  \EE[t^X] = \sum_{k=1}^{\infty}t^{k}\PP(X=k) = \sum_{k=1}^{\infty}t^{k}(1-p)^k\frac{p}{1-p}=\frac{pt}{1-(1-p)t}
$$
ceea ce ne conduce la 
$$
  \EE\left[\frac{1}{X}\right] = \int_{0}^{1}\frac{1}{t}\frac{pt}{1-(1-p)t}\, dt = -\frac{p}{1-p}\ln(p).
$$
Dac\u a alegem s\u a definim variabila geometric\u a prin $X=\sum_{k\geq0}p(1-p)^{k}\e_{k}$ atunci $\EE\left[\frac{1}{X}\right]=+\infty$.

  
### Exerci\c tiul 3

  a) Observ\u am c\u a:
$$\PP(X>n)=\PP(X=n+1)+\PP(X=n+2)+\dots=\sum_{k=n+1}^{\infty}{\PP(X=k)}$$
\c si
\begin{align*}
\sum_{n=0}^{\infty}{\sum_{k=n+1}^{\infty}{\PP(X=k)}}&=(\PP(X=1)+\PP(X=2)+\dots)+(\PP(X=2)+\PP(X=3)+\dots)\\
  &+(\PP(X=3)+\PP(X=4)+\dots)+\dots\\
  &=1\cdot\PP(X=1)+2\cdot\PP(X=2)+3\cdot\PP(X=3)+\dots\\
  &=\sum_{k=1}^{\infty}{k\PP(X=k)}=\sum_{k=0}^{\infty}{k\PP(X=k)}=\EE[X].
\end{align*}
O alt\u a idee ar fi s\u a lu\u am $X=\sum_{i=0}^{\infty}\1_{\{X>i\}}$ \c si s\u a invers\u am $\sum$ cu $\EE$ (de ce putem ?).

  b) Avem 
$$
  \displaystyle\int_{0}^{+\infty}\PP(X\geq x)\, dx = \displaystyle\int_{0}^{+\infty}\EE[\1_{\{X\geq x\}}]\, dx \stackrel{\text{Tonelli-Fubini}}{=} \EE\left[\int_{0}^{\infty}\1_{\{X\geq x\}}\, dx\right] = \EE\left[\int_{0}^{X}\, dx\right] = \EE[X].
$$

### Exerci\c tiul 4

  a) Dac\u a $X\sim Exp(\a)$ atunci densitatea sa este $f(x) = \a e^{-\a x}\1_{(0,\infty)}(x)$ \c si are func\c tia de reparti\c tie $F(x) = (1-e^{-\a x})\1_{(0,\infty)}(x)$. Observ\u am c\u a $\PP(X>t) = 1-\PP(X\leq t) = 1-F(t) = e^{-\a t}$, deci
\begin{align*}
    \PP(X>t+s|X>s) &= \frac{\PP(X>t+s,X>s)}{\PP(X>s)} = \frac{\PP(X>t+s)}{\PP(X>s)} = \frac{e^{-\a(t+s)}}{e^{-\a st}} = e^{-\a t} = \PP(X>t).
\end{align*}

\underline{Interpretare:} S\u a presupunem c\u a $X$ reprezint\u a durata de via\c t\u a a unei componente electrice. \c Stiind c\u a  $X$ a func\c tionat deja un timp $s$ ($X>s$), probabilitatea ca $X$ s\u a func\c tioneze un timp $t$ suplimentar ($X>t+s$) este egal\u a cu probabilitatea ca $X$ s\u a func\c tioneze un timp $t$. Faptul c\u a a func\c tionat deja un timp $s$ nu influen\c teaz\u a probabilitatea s\u a func\c tioneze un timp $t$ in plus.
  
  b) Din rela\c tia 
$$
\PP(X>s+t|X>s)=\frac{\PP(X>s+t,X>s)}{\PP(X>s)}=\frac{\PP(X>s+t)}{\PP(X>s)}=\PP(X>t)
$$
ob\c tinem $\PP(X>s+t)=\PP(X>s)\PP(X>t)$ de unde notand cu $h(t)=\PP(X>t)$ avem $h(s+t)=h(s)h(t)$ pentru $s>0,\ t>0$. 

Pentru a verifica c\u a v.a. $X$ este distribuit\u a exponen\c tial trebuie s\u a rezolv\u am ecua\c tia func\c tional\u a Cauchy. Observ\u am pentru inceput c\u a dac\u a $s=t$ atunci $h(2s)=h^2(s)$ \c si prin induc\c tie avem $h(ks)=h^k(s)$ pentru $k\in\NN$. Luand $s=\frac{1}{2}$ avem $h(1)=h^2(\frac{1}{2})$ de unde $h(\frac{1}{2})=h^{\frac{1}{2}}(1)$ \c si pentru $s=\frac{1}{k}$ rezult\u a c\u a  $h(\frac{1}{k})=h^{\frac{1}{k}}(1)$ (prin aceea\c si argumentare). Combinand rezultatele avem $h(\frac{m}{n})=h(m\frac{1}{n})=h^m(\frac{1}{n})=h^{\frac{m}{n}}(1)$. Prin urmare $h(q)=h^q(1)$ pentru orice $q\in\QQ_+$. Dac\u a $r\in \RR_+-\QQ_+$ exist\u a un \c sir $(q_n)_n\subset\QQ_+$ a\c sa incat $q_n\downarrow r$ \c si folosind continuitatea la dreapta avem $h(q_n)\downarrow h(r)$ deci $h(r)=a^r$, unde $a=h(1)$. In final am g\u asit c\u a $h(t)=e^{-t\log{\frac{1}{h(1)}}}$.

### Exerci\c tiul 5

  a) Este defini\c tia binomialei. Avem $\EE[S_n]=np$ \c si $\VV[S_n] = np(1-p)$.
  
  b) Avem c\u a $\{L=n\}=\{X_1=\cdots=X_n=1,X_{n+1}=0\}\cup\{X_1=\cdots=X_n=0,X_{n+1}=1\}$ de unde $\PP(L=n)=p^nq+pq^n$, $n\geq1$, $q=1-p$. Rezult\u a c\u a 
  \begin{align*}
    \EE[L] &= \sum_{n\geq1} n\PP(L=n) = \sum_{n\geq1} n(p^nq+pq^n) = 2+\frac{(p-q)^2}{pq}\\
    \VV[L] &= \sum_{n\geq1} n^2\PP(L=n) - \EE[L]^2 = 2+\frac{(1+pq)(p-q)^2}{p^2q^2}
  \end{align*}
  Pentru a g\u asi legea lui $M$ s\u a ne uit\u am la cuplul $(L,M)$ \c si s\u a observ\u am c\u a evenimentul $\{L=n, M=m\}$ este dat de $\{X_1=\cdots=X_n=1,X_{n+1}=\cdots=X_{n+m}=0,X_{n+m+1}=1\}\cup\{X_1=\cdots=X_n=0,X_{n+1}=\cdots=X_{n+m}=1,X_{n+m+1}=0\}$ de unde 
  \begin{align*}
    \PP(L=n,M=m) &= \PP(X_1=\cdots=X_n=1,X_{n+1}=\cdots=X_{n+m}=0,X_{n+m+1}=1) +\\           &\; \PP(X_1=\cdots=X_n=0,X_{n+1}=\cdots=X_{n+m}=1,X_{n+m+1}=0)= p^nq^mp+p^mq^nq
  \end{align*}
\c si prin urmare legea lui $M$ este
  \begin{align*}
    \PP(M=m) &= \sum_{n\geq1}\PP(L=n,M=m)= q^{m-1}p^2+p^{m-1}q^2.
  \end{align*}
Ob\c tinem asfel c\u a $\EE[M]=2$ (independent de $p$) \c si c\u a 
$$
  \VV[M] = 2+\frac{2(p-q)^2}{pq}.
$$
  
  c) Este evident c\u a $\EE[L]=2+\frac{(p-q)^2}{pq} \geq 2=\EE[M]$ \c si c\u a $\VV[L]=2+\frac{(1+pq)(p-q)^2}{p^2q^2}\geq 2+\frac{2(p-q)^2}{pq}=\VV[M]\geq 2$. Se poate calcula u\c sor c\u a 
  $$
    \EE[LM] = \sum_{n,m\geq1}nm\PP(L=n,M=m) = \frac{1}{pq}
  $$
de unde rezult\u a c\u a $Cov[L,M] = -\frac{(p-q)^2}{pq}$.  

  d) Observ\u am c\u a 
  $$
    \displaystyle\lim_{k\to\infty}\PP(M=n\,|\,L=k)=\lim_{k\to\infty}\frac{\PP(L=k,M=n)}{\PP(L=k)}=\lim_{k\to\infty}\frac{p^{k+1}q^n+q^{k+1}p^{n}}{p^kq+q^kp}
  $$
\c si studiind comportamentul raportului $\frac{p}{q}$ (dac\u a este $>1$ sau nu dup\u a cum e $p$) deducem c\u a 
$$
  \displaystyle\lim_{k\to\infty}\PP(M=n\,|\,L=k)=\left\{\begin{array}{lll}
        p^{n-1}q, & \mbox{dac\u a $p<\frac{1}{2}$}\\
        q^{n-1}p, & \mbox{dac\u a $p>\frac{1}{2}$}\\
        2^{-n}, & \mbox{dac\u a $p=\frac{1}{2}$}\\
  \end{array}\right.
$$
