---
title: "Tema 3"
subtitle: "(predare pana pe 04.11.16)"
output:
  pdf_document:
    includes:
      before_body: Defs/body.tex
      in_header: Defs/FormatAndDefs.tex
    keep_tex: yes
    toc: no
  html_document:
    fig_caption: yes
    toc: yes
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Exerci\c tiul 1
O urn\u a con\c tine $r$ bile ro\c sii \c si $b$ bile albastre. O bil\u a este extras\u a la intamplare din urn\u a, i se noteaz\u a culoarea \c si este intoars\u a in urn\u a impreun\u a cu alte $d$ bile de aceea\c si culoare. Repet\u am acest proces la nesfar\c sit. Calcula\c ti:

  a) Probabilitatea ca a doua bil\u a extras\u a s\u a fie albastr\u a.
  
  b) Probabilitatea ca prima bil\u a s\u a fie albastr\u a \c stiind c\u a a doua bil\u a este albastr\u a. 
  
  c) Fie $B_n$ evenimentul ca a $n$-a bil\u a extras\u a s\u a fie albastr\u a. Ar\u ata\c ti c\u a $\PP(B_n)=\PP(B_1)$, $\forall\, n\geq1$.
  
  d) Probabilitatea ca prima bil\u a este albastr\u a \c stiind c\u a urm\u atoarele $n$ bile extrase sunt albastre. G\u asi\c ti valoarea limit\u a a acestei probabilit\u a\c ti. 

### Exerci\c tiul 2
\c Stim c\u a intr-un lot de $5$ tranzistori avem $2$ care sunt defec\c ti. Tranzistorii sunt testa\c ti, unul cate unul, pan\u a cand cei doi tranzistori au fost identifica\c ti. Fie $N_1$ num\u arul de teste pentru identificarea primului tranzistor defect \c si $N_2$ num\u arul de teste suplimentare pentru identificarea celui de-al doilea tranzistor defect. Scrie\c ti un tablou in care s\u a descrie\c ti legea cuplului $(N_1,N_2)$. Calcula\c ti $\EE[N_1]$ \c si $\EE[N_2]$.
  
### Exerci\c tiul 3
Fie $(X_1,X_2)$ vectorul aleator distribuit uniform pe discul $D(R)$ centrat in origine \c si de raz\u a $R$. Densitatea vectorului $(X_1,X_2)$ este dat\u a de 
$$
  f(x_1,x_2) = c\1_{D(R)}(x_1,x_2)
$$
unde $c$ este o constant\u a pozitiv\u a.

  1. Determina\c ti constanta $c$.
  
  2. Determina\c ti legile marginale ale lui $X_1$ \c si $X_2$.
  
  3. Fie $L$ distan\c ta de la punctul $(X_1,X_2)$ la origine. G\u asi\c ti func\c tia de reparti\c tie a lui $L$, legea lui $L$ \c si media sa.






