---
title: "Tema 1"
subtitle: "Câmp de probabilitate, operații cu evenimente, probabilitate conditionată și formula lui Bayes"
output:
  pdf_document:
    includes:
      before_body: Defs/body.tex
      in_header: Defs/FormatAndDefs.tex
    keep_tex: yes
    toc: no
  html_document:
    fig_caption: yes
    toc: yes
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Exerci\c tiul 1
Fie $A$, $B$ \c si $C$ trei evenimente. Exprima\c ti $\^ i$n func\c tie de $A$, $B$, $C$ \c si de opera\c tiile cu mul\c timi urm\u atoarele evenimente: 

  a) $A$ singur se realizeaz\u a
  
  b) $A$ \c si $C$ se realizeaz\u a dar nu \c si $B$
  
  c) cele trei evenimente se produc
  
  d) cel pu\c tin unul dintre cele trei evenimente se produce
  
  e) cel pu\c tin dou\u a evenimente din cele trei se produc 
  
  f) cel mult un eveniment se produce
  
  g) niciunul din cele trei evenimente nu se produce
  
  h) exact dou\u a evenimente din cele trei se produc 
  
  i) nu mai mult de dou\u a evenimente nu se realizeaz\u a 

### Exerci\c tiul 2
Fie $\Om$ mul\c timea tuturor cuplurilor c\u as\u atorite dintr-un ora\c s dat. Consider\u am evenimentele urm\u atoare: 

  $A$: "b\u arbatul are mai mult de 40 de ani"
  
  $B$: "femeia este mai t$\^ a$n\u ar\u a dec$\^ a$t b\u arbatul"
  
  $C$: "femeia are mai mult de 40 de ani"
  
Se cere: 

  a) Interpreta\c ti in func\c tie de $A$, $B$ \c si $C$ evenimentul "so\c tul are mai mult de 40 de ani dar nu \c si so\c tia sa".
  
  b) Descrie\c ti in limbaj natural evenimentele: $A\cap B\cap C^{c}$, $A\setminus{(A\cap B)}$ , $A\cap B^{c}\cap C$, $A\cup B$
  
  c) Verifica\c ti c\u a $A\cap C^{c} \subset B$

### Exerci\c tiul 3
Fie $(\Om, \MF, \PP)$ un c$\^a$mp de probabilitate. Diferen\c ta simetric\u a dintre dou\u a evenimente $A, B\in \MF$ este definit\u a prin $A	\triangle B=(A\cap B^{c})\cup(A^{c}\cap B)$. Ar\u ata\c ti c\u a:

  a) func\c tia $d(A,B)=\PP(A\triangle B)$ este o distan\c t\u a pe $\MF$
  
  b) $|\PP(A)-\PP(B)|\leq\PP(A\triangle B)$
  
### Exerci\c tiul 4
Fie $n$, $r>1$ numere naturale \c si consider\u am ecua\c tia cu $r$ necunoscute:
$$
x_1+x_2+\cdots+x_r=n.
$$
O solu\c tie a acestei ecua\c tii este un $r$-tuplu $(x_1, \dots, x_r)$ a c\u arui sum\u a a componentelor este $n$.

  a) C$\^a$te solu\c tii are ecua\c tia de mai sus, cu componente naturale strict pozitive ?
  
  b) C$\^a$te solu\c tii are ecua\c tia de mai sus, cu componente naturale pozitive ?

### Exerci\c tiul 5
Un administrator de spital codific\u a pacien\c tii cu r\u ani prin $\^i$mpu\c scare $\^i$n func\c tie de asigurarea ($D$ dac\u a pacientul are asigurare \c si $N$ dac\u a nu are) \c si de starea acestora ($b$ pentru bun\u a, $m$ pentru medie \c si $s$ pentru serioas\u a). Consider\u am experien\c ta aleatoare care consist\u a in codificarea pacien\c tilor. 

  1.  a) Determina\c ti $\Om$ mul\c timea spa\c tiului st\u arilor acestui experiment
      b) Fie $A$ evenimentul *starea de s\u an\u atate a pacientului este serioas\u a*. Descrie\c ti evenimentele elementare care il compun pe $A$. Aceea\c si intrebare pentru evenimentul $B$ *pacientul nu este asigurat* \c si pentru evenimentul $B^c\cup A$.
      
  2. Consider\u am echiprobabilitatea pe $\Om$. Calcula\c ti probabilit\u a\c tile: $\PP(A)$, $\PP(B)$ \c si $\PP(B^c\cup A)$
  
  3. Aceea\c si intrebare pentru probabilitatea $\PP'$ definit\u a prin 
  
  \begin{center}
    \begin{tabular}{c|ccc}
        & $b$ & $m$ & $s$ \\
      \hline
      $O$ & $0,2$ & $0,2$ & $0,1$ \\
      $N$ & $0,1$ & $0,3$ & $0,1$ \\
    \end{tabular}
  \end{center}

### Exerci\c tiul 6 (Jocul de Poker)
Consider\u am experimentul in care extragem o man\u a de $5$ c\u ar\c ti dintr-un pachet de c\u ar\c ti de $52$ de c\u ar\c ti. S\u a se calculeze probabilitatea ca: 
  
  a) S\u a avem careu (patru c\u ar\c ti de acela\c si tip) ?
  
  b) S\u a avem full-house (trei c\u ar\c ti de un tip \c si dou\u a de altul) ? 
  
  c) S\u a avem trei c\u ar\c ti de acela\c si tip ?
  
  d) S\u a avem dou\u a perechi ?
    
  e) S\u a avem o pereche ?
  

### Exerci\c tiul 7
Se dore\c ste verificarea fiabilit\u a\c tii unui test de pentru depistarea nivelului de alcool al automobili\c stilor. In urma studiilor statistice pe un num\u ar mare de automobili\c sti, s-a observat c\u a in general $0.5\%$ dintre ace\c stia dep\u a\c sesc nivelul de alcool autorizat. Niciun test nu este fiabil $100\%$. Probabilitatea ca testul considerat s\u a fie pozitiv atunci cand doza de alcool autorizat\u a este dep\u a\c sit\u a precum \c si probabilitatea ca testul s\u a fie negativ atunci cand doza autorizat\u a nu este dep\u a\c sit\u a sunt egale cu $p=0.99$. 

  1. Care este probabilitatea ca un automobilist care a fost testat pozitiv s\u a fi dep\u a\c sit in realitate nivelul de alcool autorizat ?
  
  2. C$\^a$t devine valoarea parametrului $p$ pentru ca aceast\u a probabilitate s\u a fie de $95\%$ ? 
  
  3. Un poli\c tist afirm\u a c\u a testul este mai fiabil samb\u ata seara (atunci c$\^a$nd tinerii ies din cluburi). \c Stiind c\u a propor\c tia de automobili\c sti care au b\u aut prea mult in acest context este de $30\%$, determina\c ti dac\u a poli\c tistul are dreptate.

### Exerci\c tiul 8
Efectu\u am arunc\u ari succesive a dou\u a zaruri echilibrate \c si suntem interesa\c ti in g\u asirea probabilit\u a\c tii evenimentului ca suma $5$ (a fe\c telor celor dou\u a zaruri) s\u a apar\u a inaintea sumei $7$. Pentru aceasta presupunem c\u a arunc\u arile sunt *independente*. 

  1. Calcula\c ti pentru inceput probabilitatea evenimentului $E_n$: *in primele $n-1$ arunc\u ari nu a ap\u arut nici suma $5$ \c si nici suma $7$ iar in a $n$-a aruncare a ap\u arut suma $5$*. Concluziona\c ti. 
  
  2. Aceea\c si intrebare, dar inlocuind $5$ cu $2$.

### Exerci\c tiul 9* ^[Exerci\c tiile cu * sunt suplimentare \c si nu sunt obligatorii]
Fie $(A_1, A_2, \dots, A_n)$, $n\geq0$ un \c sir de p\u ar\c ti ale lui $\Om$ \c si $\MF$ algebra generat\u a de acesta (cea mai mic\u a algebr\u a in sensul incluziunii care con\c tine \c mul\c timile $\{A_1, A_2, \dots, A_n\}$). Fie $(c_1, \dots,c_m)$ un \c sir de numere reale \c si $(B_1, B_2, \dots, B_m)$ un \c sir de elemente din $\MF$ ($m\geq 0$). Consider\u am inegalitatea
\begin{equation}\label{eq1}
  \displaystyle\sum_{k=1}^{m}c_k\PP(B_k)\geq 0
\end{equation}
unde $\PP$ este o m\u asur\u a de probabiilitate pe $\MF$. Urm\u atoarele propriet\u a\c ti sunt echivalente: 

  a) Inegalitatea $(\ref{eq1})$ este adev\u arat\u a pentru toate m\u asurile de probabilitate $\PP$ pe $\MF$
  
  b) Inegalitatea $(\ref{eq1})$ este adev\u arat\u a pentru toate m\u asurile de probabilitate $\PP$ pe $\MF$ care verific\u a $\PP(A_i)=0$ sau $1$, pentru to\c ti $i\in\{1,2,\dots,n\}$.

### Exerci\c tiul 10*

Fie $S_{0}^{n}=1$, $S_{k}^{n}=\displaystyle\sum_{1\leq i_1<\cdots<i_k\leq n}\PP\left(A_{i_1}\cap\cdots\cap A_{i_k}\right)$ \c si not\u am cu $V_{n}^{r}$ (respectiv cu $W_{n}^{r}$) probabilitatea ca exact $r$ (respectiv cel pu\c tin $r$) dintre evenimentele $A_1, A_2, \dots, A_n$ se realizeaz\u a. Ar\u ata\c ti c\u a: 

  a) $V_{n}^{r}=\displaystyle\sum_{k=0}^{n-r}(-1)^k\binom{r+k}{k}S_{r+k}^{n}$
  
  b) $W_{n}^{r}=\displaystyle\sum_{k=0}^{n-r}(-1)^k\binom{r+k-1}{k}S_{r+k}^{n}$




