---
title: "Tema 2"
subtitle: ""
output:
  pdf_document:
    includes:
      before_body: Defs/body.tex
      in_header: Defs/FormatAndDefs.tex
    keep_tex: yes
    toc: no
  html_document:
    fig_caption: yes
    toc: yes
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Exerci\c tiul 1
O urn\u a con\c tine $r$ bile ro\c sii \c si $b$ bile albastre. O bil\u a este extras\u a la intamplare din urn\u a, i se noteaz\u a culoarea \c si este intoars\u a in urn\u a impreun\u a cu alte $d$ bile de aceea\c si culoare. Repet\u am acest proces la nesfar\c sit. Calcula\c ti:

  a) Probabilitatea ca a doua bil\u a extras\u a s\u a fie albastr\u a.
  
  b) Probabilitatea ca prima bil\u a s\u a fie albastr\u a \c stiind c\u a a doua bil\u a este albastr\u a. 
  
  c) Fie $B_n$ evenimentul ca a $n$-a bil\u a extras\u a s\u a fie albastr\u a. Ar\u ata\c ti c\u a $\PP(B_n)=\PP(B_1)$, $\forall\, n\geq1$.
  
  d) Probabilitatea ca prima bil\u a este albastr\u a \c stiind c\u a urm\u atoarele $n$ bile extrase sunt albastre. G\u asi\c ti valoarea limit\u a a acestei probabilit\u a\c ti. 

### Exerci\c tiul 2
O companie de asigur\u ari asigur\u a acela\c si num\u ar de b\u arba\c ti \c si de femei. Intr-un an dat, probabilitatea ca un b\u arbat s\u a fac\u a accident \c si s\u a aib\u a nevoie de asigurare este de $\a$, independent de al\c ti ani. In mod similar, probabilitatea ca o femeie s\u a fac\u a accident \c si s\u a beneficieze de asigurare este $\b$. S\u a presupunem c\u a firma de asigur\u ri alege la intamplare o persoan\u a. 

  a) Care este probabilitatea ca \c soferul ales s\u a aib\u a nevoie de o poli\c t\u a de asigurare anul acesta ?
  
  b) Care este probabilitatea ca \c soferul ales s\u a aib\u a nevoie de asigurare doi ani la rand ?
  
  c) Fie $A_1, A_2$ evenimentele prin care \c soferul ales are nevoie de asigurare in primul, respectiv cel de-al doilea an. Ar\u ata\c ti c\u a $\PP(A_2|A_1)\geq\PP(A_1)$. 
  
  d) G\u asi\c ti probabilitatea ca persoana care are nevoie de asigurare s\u a fie o femeie.

### Exerci\c tiul 3
Fie $X$ o variabil\u a aleatoare de densitate: 
$$
  f(x) = \left\{\begin{array}{ll}
    \frac{2x}{\t^2}, & \mbox{dac\u a $0\leq x\leq \t$}\\
    0, & \mbox{altfel}
  \end{array}\right.
$$
unde $\t$ este un num\u ar pozitiv dat. Determina\c ti func\c tia de reparti\c tie, media \c si varian\c ta lui $X$.

### Exerci\c tiul 4
Fie $X$ o variabil\u a aleatoare a c\u arei func\c tie de reparti\c tie este 

$$
  F(x) = \left\{\begin{array}{lll}
    0, & \mbox{dac\u a $x\leq1$}\\
    \ln(x), & \mbox{dac\u a $1<x\leq e$}\\
    1, & \mbox{dac\u a $e<x$}
  \end{array}\right.
$$

Calcula\c ti $\EE[X]$ \c si $\VV[X]$.

### Exerci\c tiul 5
Fie $X$ o variabil\u a aleatoare de densitate: 
$$
  f(x) = \left\{\begin{array}{ll}
    e^{-(x-\t)}, & \mbox{dac\u a $x>\t$}\\
    0, & \mbox{altfel}
  \end{array}\right.
$$
unde $\t$ este un num\u ar real dat.

  a) Determina\c ti func\c tia de reparti\c tie, media, varian\c ta \c si mediana acestei variabile
  
  b) Fie $X_1,\cdots,X_n$ variabile aleatoare independente de aceea\c si lege ca \c si $X$ \c si fie $m_n=\min(X_1,\cdots,X_n)$. Determina\c ti func\c tia de reparti\c tie \c si densitatea variabilei aleatoare $m_n$.

### Exerci\c tiul 6
Fie $X$ o variabil\u a aleatoare de densitate: 
$$
  f(x) = \left\{\begin{array}{ll}
    \frac{1}{\t}x^{\frac{1}{\t}-1}, & \mbox{dac\u a $0\leq x\leq 1$}\\
    0, & \mbox{altfel}
  \end{array}\right.
$$
unde $\t$ este un num\u ar pozitiv dat. Determina\c ti legea variabilei aleatoare $Y=-\ln(X)$.


